---
title: "Main Analysis"
format: html
---

# Main Analysis

## Assessing Total U.S. Food Imports Volume Over Time

```{r}
volume |>
  filter(Measurement == "1,000 mt") |>
  ggplot(
    aes(x = Year, y = Imports, color = Category)) +
  geom_line() +
  scale_color_viridis_d(option = "turbo") +
  theme_minimal() +
  labs(
    title = "U.S. Food Imports Volume Over Time, by Category (1999-2024)",
    x = "Year",
    y = "Imports (1,000 metric tons)"
  )
```


## Assessing Percent Change in U.S. Food Import Volume, 2005-2006

```{r}
volume_perc |>
  filter(Year == "2006") |>
  ggplot(
    aes(x = reorder(Category, Imports), 
        y = Imports,
        fill = Category)) +
  geom_col() +
  scale_fill_viridis_d(option = "turbo") +
  theme(axis.text.x = element_blank()) +
  labs(
    title = "Percent Change U.S. Food Import Volume by Category, 2005-2006",
    x = "",
    y = "Percent Change")
```


## Assessing Percent Change in U.S. Food Import Volume, 2008-2009

```{r}
volume_perc |>
  filter(Year == "2009") |>
  ggplot(
    aes(x = reorder(Category, Imports), 
        y = Imports,
        fill = Category)) +
  geom_col() +
  scale_fill_viridis_d(option = "turbo") +
  theme(axis.text.x = element_blank()) +
  labs(
    title = "Percent Change U.S. Food Imports by Category, 2008-2009",
    x = "",
    y = "Percent Change")
```


## Assessing Total Percent Change in U.S. Food Import Volume Between 2005-2006 and 2008-2009

```{r}
data_06 <- volume_perc |>
  filter(Year == "2006") |>
  select(Category, imp_2006 = Imports)

data_09 <- volume_perc |>
  filter(Year == "2009") |>
  select(Category, imp_2009 = Imports)

sum_diff_06_09 <- data_06 |>
  left_join(data_09, by = "Category") |>
  mutate(diff = abs(imp_2009) + abs(imp_2006)) |>
  rename(
    "Percent Change 2005-2006" = imp_2006,
    "Percent Change 2008-2009" = imp_2009,
    "Total Percent Change" = diff) |>
  arrange(desc(`Total Percent Change`))


sum_diff_06_09
```
